# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "accesses", :force => true do |t|
    t.column "company", :string
    t.column "locked",  :boolean
  end

  create_table "dishes", :force => true do |t|
    t.column "number",      :string
    t.column "description", :string
    t.column "price",       :float
    t.column "category",    :string
  end

  create_table "engine_schema_info", :id => false, :force => true do |t|
    t.column "engine_name", :string
    t.column "version",     :integer
  end

  create_table "orders", :force => true do |t|
    t.column "person",       :string
    t.column "order",        :integer
    t.column "dish_id",      :integer
    t.column "note",         :string
    t.column "paid",         :boolean
    t.column "machine_name", :string
    t.column "company",      :string
  end

  create_table "permissions", :force => true do |t|
    t.column "controller",  :string, :default => "", :null => false
    t.column "action",      :string, :default => "", :null => false
    t.column "description", :string
  end

  create_table "permissions_roles", :id => false, :force => true do |t|
    t.column "permission_id", :integer, :default => 0, :null => false
    t.column "role_id",       :integer, :default => 0, :null => false
  end

  create_table "roles", :force => true do |t|
    t.column "name",        :string,  :default => "",    :null => false
    t.column "description", :string
    t.column "omnipotent",  :boolean, :default => false, :null => false
    t.column "system_role", :boolean, :default => false, :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "login",           :string,   :limit => 80, :default => "", :null => false
    t.column "salted_password", :string,   :limit => 40, :default => "", :null => false
    t.column "email",           :string,   :limit => 60, :default => "", :null => false
    t.column "firstname",       :string,   :limit => 40
    t.column "lastname",        :string,   :limit => 40
    t.column "salt",            :string,   :limit => 40, :default => "", :null => false
    t.column "verified",        :integer,                :default => 0
    t.column "role",            :string,   :limit => 40
    t.column "security_token",  :string,   :limit => 40
    t.column "token_expiry",    :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "logged_in_at",    :datetime
    t.column "deleted",         :integer,                :default => 0
    t.column "delete_after",    :datetime
  end

  create_table "users_roles", :id => false, :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "role_id", :integer, :default => 0, :null => false
  end

end
